<?php
return [
	'' =>	'- Select -',
	'Hyderabad' =>	'HYDERABAD',
	'Malkajgiri' =>	'MALKAJGIRI',
	'Rangareddy (Cyberabad)' =>	'RANGAREDDY (CYBERABAD)',
	'Vikarabad' =>	'VIKARABAD',
	'Mancherial' =>	'MANCHERIAL',
	'Nirmal' =>	'NIRMAL',
	'Karimnagar' =>	'KARIMNAGAR',
	'Jagtial' =>	'JAGTIAL',
	'Peddapalli' =>	'PEDDAPALLI',
	'Khammam' =>	'KHAMMAM',
	'Hanumakonda' =>'HANUMAKONDA',
	'Bhupalpally' =>'BHUPALPALLY',
	'Nizamabad' =>'NIZAMABAD',
	'Kamareddy' =>'KAMAREDDY',
	'Sangareddy' =>	'SANGAREDDY',
	'Medak' =>	'MEDAK',
	'Nalgonda' =>'NALGONDA',
	'Suryapet' =>'SURYAPET',
	'Yadadri Bhuvanagiri' =>'YADADRI BHUVANAGIRI',
	'Mahabubnagar' =>'MAHABUBNAGAR',
	 'Gadwal' => 'GADWAL',
	'Wanaparthy' =>	'WANAPARTHY',
	'Adilabad' =>	'ADILABAD',
	'Siricilla' =>	'SIRICILLA',
	'Mulugu' =>	'MULUGU',
	'Jangaon' =>	'JANGAON',
	'Warangal Rural' =>	'WARANGAL RURAL',
	'Mahabubabad'=>'MAHABUBABAD',
	'Siddipet' =>'SIDDIPET',
	'Nagarkurnool'=>'NAGARKURNOOL',
	'Narayanpet'=>	'NARAYANPET',

];