<?php
return [
    '' => [],
    'east' => [
        '' => '',
		'br' => 'Bihar',
		'jh' => 'Jharkhand',
		'od' => 'Odisha',
		'wb' => 'West Bengal',
    ],
	'west' => [
        '' => '',
		'dn' => 'Dadra & Nagar Haveli',
		'dd' => 'Daman & Diu',
		'ga' => 'Goa',
		'gj' => 'Gujarat',
		'mh' => 'Maharashtra',
        'rj' => 'Rajasthan',
    ],
	'northeast' => [
        '' => '',
        'ar' => 'Arunachal Pradesh',
		'as' => 'Assam',
        'mn' => 'Manipur',
		'ml' => 'Meghalaya',
		'mz' => 'Mizoram',
		'nl' => 'Nagaland',
		'sk' => 'Sikkim',
		'tr' => 'Tripura',
    ],
	'north' => [
        '' => '',
		'ch' => 'Chandigarh',
		'dl' => 'Delhi',
		'hr' => 'Haryana',
		'hp' => 'Himachal Pradesh',
        'jk' => 'Jammu & Kashmir',
		'pb' => 'Punjab',
		'uk' => 'Uttarakhand',
		'up' => 'Western Uttar Pradesh',
    ],
	'central' => [
        '' => '',
		'cg' => 'Chhattisgarh',
        'eup' => 'Eastern Uttar Pradesh',
		'emp' => 'Eastern Madhya Pradesh',
		'wmp' => 'Western Madhya Pradesh',
    ],
	'south1' => [
        '' => '',
        'ap' => 'Andhra Pradesh',
        'ka' => 'Karnataka',
        'ts' => 'Telangana',
    ],
	'south2' => [
        '' => '',
		'an' => 'Andaman and Nicobar Island',
		'kl' => 'Kerala',
		'py' => 'Puducherry',
		'tn' => 'Tamil Nadu',
    ]
];